[package]
authors = ["Zeyla Hellyer <zey@zey.moe>"]
description = "A Rust library for the Discord API."
documentation = "https://serenity.zey.moe"
homepage = "https://github.com/zeyla/serenity"
keywords = ["discord", "api"]
license = "ISC"
name = "serenity"
readme = "README.md"
repository = "https://github.com/zeyla/serenity.git"
version = "0.2.0"

[dependencies]
base64 = "~0.5"
bitflags = "~0.8"
flate2 = "~0.2"
hyper = "~0.9"
lazy_static = "~0.2"
log = "~0.3"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
time = "~0.1"
typemap = "~0.3"
websocket = "~0.17"

[dependencies.byteorder]
optional = true
version = "1.0"

[dependencies.cookie]
default-features = false
version = "0.2"

[dependencies.multipart]
default-features = false
features = ["client", "hyper"]
version = "0.8"

[dependencies.opus]
optional = true
version = "0.1"

[dependencies.sodiumoxide]
default-features = false
optional = true
version = "0.0.12"

[features]
default = ["cache", "framework"]
cache = []
debug = []
framework = []
extras = []
voice = ["byteorder", "opus", "sodiumoxide"]
