control_style = "Legacy"
fn_args_layout = "visual"
fn_brace_style = "PreferSameLine"
fn_single_line = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
item_brace_style = "PreferSameLine"
match_block_trailing_comma = true
normalize_comments = true
reorder_imported_names = true
struct_lit_multiline_style = "ForceMulti"
use_try_shorthand = true # just to be safe
where_layout = "HorizontalVertical"
where_style = "Legacy"
wrap_comments = true
comment_width = 115
closure_block_indent_threshold = 1
chain_split_single_child = true
condense_wildcard_suffixes = true